### ISSUE TITLE
how install policy templates

### ISSUE THREAD

**Issue by huv9** [Alex313031/thorium-legacy#100]
hi
windows 7 I know my question is stupid But it's complicated for me I have three files adm-adml-examples Because I want to use it I would like an explanation from you on how to add it
https://github.com/Alex313031/thorium-legacy/releases/download/M122.0.6261.171/thorium_policy_templates.zip

**Comment by gz83** [comment]
https://support.google.com/chrome/a/answer/187202?hl=en&sjid=4039585407906824736-AP

Please see the page above, and you should be able to find more information on how to use policy templates by searching the Internet.
