### ISSUE TITLE
Ungoogled version for legacy

### ISSUE THREAD

**Issue by c33s** [Alex313031/thorium-legacy#106]
coming from [ungoogled chromium][uc] i am used to have a non-working google app store page and other things which don't work out of the box. switching to thorium made me notice that the app store is working  without any problems. checking with the [faq][faq] i read that it will never be a full ungoogled app. 

my feature request would be to release a ungoogled version for thorium-legacy as it would be the only source (i know) with a chrome version which works on win7 and is ungoogled.

i would oppose your following statement from the faq:

> ... contains no personally identifiable information (PII) that could be used to identify you.

as the browser connects with my ip address to the google service and an [ip address counts as PII][gdpr] (even if the eu would not count it as identifier, it is a very good identifier from a reality/technical point of view).

from this point of view i would also love to see an ungoogled version in the regular version of thorium 

[uc]: https://chromium.woolyss.com/
[faq]: https://github.com/Alex313031/thorium-legacy/blob/main/docs/FAQ.md
[gdpr]: https://gdpr.eu/eu-gdpr-personal-data/

**Comment by gz83** [comment]
https://github.com/Alex313031/thorium/issues/454

**Comment by c33s** [comment]
@gz83 isn't this a valid request for win7? the faq answer doesn't really apply as there are no alternatives (=ungoogled chromium) for win7 any more.

**Comment by gz83** [comment]
FAQ Q4 has answered your question

**Comment by c33s** [comment]
i explicitly quoted a text from faq q4 which i think is not correct (PII) and brought up the special case for win7.
