### ISSUE TITLE
Chromium unicode fallback mechanism broken for Win7

### ISSUE THREAD

**Issue by Templayer** [Alex313031/thorium-legacy#16]
**System Details**
 - OS: Windows 7 64-bit Ultimate
 - Thorium Version - Any Chromium-based browser, really, but Thorium 109.0.5414.159 64-bit

**Problem**
It seems like Chromium and Chromium-based browsers have problems with Unicode fallback mechanisms under Win7. See screenshots for more details. I just noticed that some pages have invalid glyphs for buttons, etc. This isn't a Thorium issue per se, but a Chromium issue with Win7 (at least it appears to be at a first glance).

How to test: Look at glyphs on https://www.amp-what.com/unicode/search/cross while having big Unicode fonts installed.

**Screenshots**
Firefox for comparison (all glyphs accounted for):

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/abbdb1d0-e01e-4da1-a3fe-d36bdf823299)

Thorium:

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/26b708a0-81a4-4989-bbf4-096409623959)

Chromium (old version):

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/0abc9e87-f3ee-455a-98ac-3745b9d7169c)

Fonts installed in the system: 

[Font List.docx](https://github.com/Alex313031/thorium-win7/files/12894900/Font.List.docx)

With fonts embedded into the docx file: UNFORTUNATELY, I CANNOT UPLOAD a 7z file due to retarded github limitations (not a supported file type!) and I had to store it in a zip file... goddamit!
[Font List.zip](https://github.com/Alex313031/thorium-win7/files/12894946/Font.List.zip)

Both Noto Sans Symbols2 and Symbola have the missing glyph. Why is Chromium/Thorium not able to check these under Win7?

**Comment by JaegerFox** [comment]
that's because chromium uses the system font, firefox uses a built-in one

**Comment by Templayer** [comment]
> that's because chromium uses the system font, firefox uses a built-in one

That doesn't sound right - are you telling me that Chromium uses only ONE singular font from the system? Which one? There are a few fonts that are used in various parts of the system.

Doesn't sound right - there is no singular font that is capable of taking the entirety of Unicode. So that would be a serious design flaw if that was the case.

Also, Firefox is capable of using system fonts with a font fallback. I noticed that when I installed a slew if huge fonts - whereas Firefox showed invalid characters for hieroglyphs, after installing those system fonts, hieroglyphs would now show up (in a very pixelated way, but still).

**Comment by gz83** [comment]
Please report this issue to Google

**Comment by Templayer** [comment]
And if it is a Win7-specific problem?

**Comment by gz83** [comment]
> And if it is a Win7-specific problem?

Try supermium and see if the problems you encountered still occur.

If supermium does not have this problem, then I will reopen this issue.

@Templayer

**Comment by JaegerFox** [comment]
Just do this test and you'll see, some sites like Twitter use a font that adds more compatibility with emojis or symbols.
but a correct way to compare is using this link
`https://unicode.org/Public/emoji/11.0/emoji-test.txt`
![Chormium](https://github.com/Alex313031/thorium-win7/assets/29095345/dff654fc-91bb-4705-b626-c42a707443a6)
![Firefox](https://github.com/Alex313031/thorium-win7/assets/29095345/d77429a8-d175-4b08-98b6-29bce14fa70e)

**Comment by Templayer** [comment]
>  (Windows 8.1 which have more symbols than win7)

Nope, I can for example use and see more symbols (when used as a file name) in Win7... than Win10. I do have a modified Segoe UI Symbol and Segoe UI Emoji, among fallback and many big fonts. :)

> Twitter

What's Twitter?

> some sites

And have you tested the very site I made printscreens of? You should've checked... ;)

**Comment by JaegerFox** [comment]
If I put that link to you it is so that you could see first hand a real test of the unicode characters without any kind of coding. ok?
the page you show me are those that use fonts modified to show that kind of characters, you have ublock origin? deactivate the fonts and do a forced refresh (shift + ctrl + R) this page uses noto family fonts not segoe fonts
by deactivating fonts with ublock you will use entirely the characters of the system.

Firefox already have embedded fonts meanwhile Chromium replace Noto sans with another similar of your system

**Comment by Templayer** [comment]
> you have ublock origin

No.

**Comment by JaegerFox** [comment]
just one last proof that this is not a Thorium problem.
![Captura](https://github.com/Alex313031/thorium-win7/assets/29095345/43d23863-5eb8-41bc-992a-b74170c1f9e4)
(left chromium vs right firefox disabled fonts using Ublock)

![Captura2](https://github.com/Alex313031/thorium-win7/assets/29095345/80232acb-c81d-4a59-b4ca-81d48e14e41d)
(same but now with fonts enabled)

**Comment by Templayer** [comment]
Yup, Supermium cannot show them either. Can somebody please place an Issue there and connect the Issues?

Thorium
![image](https://github.com/Alex313031/thorium-win7/assets/11728067/437f8347-9968-45a9-8e07-3b34c4f9e1c9)

Supermium
![image](https://github.com/Alex313031/thorium-win7/assets/11728067/0aab1b3c-68eb-4b8b-8d03-31f008e43252)

Firefox
![image](https://github.com/Alex313031/thorium-win7/assets/11728067/f3aea1f7-8e2c-4daa-9be6-e8824774aca2)

**Comment by Templayer** [comment]
@Alex313031 

Just by the way, this is still an issue. Maybe the Supermium author could work on this, now that we have GDI font rendering back?

https://www.amp-what.com/unicode/search/rock

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/63236360-704b-4143-bb65-dc65fa72ed16)

https://www.fontspace.com/unicode/char/1F66E-rightwards-rocket

I have both of these installed,...

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/69b3f7ba-6cf1-40f1-a9d9-181819f7afa9)

...yet I do not see the symbols.

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/cad753b5-84da-4e41-9923-a53141217364)

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/faf2c00b-619e-4b26-bc54-a9b9695bc1bd)

(The Install button is disabled because those are already installed...)

**Comment by Alex313031** [comment]
@JaegerFox @gz83 @Templayer Seems this isn't a Thorium specific problem, and y'all are also running modified Windows OSes. I cant devote time to this because there is already a backlog of work that needs to be done in both Thorium and Mercury. Sorry. If Supermium or upstream makes a fix for this, lemme know and I'll add it to the codebase.

**Comment by Templayer** [comment]
> @JaegerFox @gz83 @Templayer Seems this isn't a Thorium specific problem, and y'all are also running modified Windows OSes. I cant devote time to this because there is already a backlog of work that needs to be done in both Thorium and Mercury. Sorry. If Supermium or upstream makes a fix for this, lemme know and I'll add it to the codebase.

Yup, I am (now) well aware that this Issue should be pushed upstream to Supermium, as was mentioned in the Issue thread by other people.

For now, I have removed the Adblock Plus filter for web fonts, because that didn't affect this Issue in any way, shape or form (the result is the same no matter if webfonts are enabled or disabled).

**Comment by Alex313031** [comment]
@Templayer Does it work OK with latest M122 and using the noto font pack?

**Comment by Templayer** [comment]
> @Templayer Does it work OK with latest M122 and using the noto font pack?

I had the Noto fonts installed when I made this issue way back.

Which was my point - the browser wasn't falling back to system fonts (like Noto) properly.

That was my entire point. Yet people were telling me that "Firefox has build in emojis and fonts".

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/248391ab-6cf0-4aac-ba77-2ed879415ba8)

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/f8ab67e9-8859-412f-acb8-2054acbcc91d)

Firefox loads Noto fonts fine. It can even show things like hieroglyphs through Noto.

Thorium:

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/7efc0e5a-b2b2-4c4c-9f79-ea4cb963d6a9)

Firefox (without using build-in stuff):

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/cedd9c08-bdc9-48da-ad56-18c5e4b5f3ea)

Firefox uses Noto Color Emoji from the system correctly:

```
samp {
  font-family: 'Noto Color Emoji', monospace;
}
```

Thorium shows that same font-family, but is unable to get the font from the operating system:

![image](https://github.com/Alex313031/thorium-win7/assets/11728067/cfa70002-a53d-44cb-a272-42ec7f6d629b)

**Comment by Templayer** [comment]
I'm starting to suspect that the only thing different is the way Firefox and Supermium enumerate system fonts.

I have weirdly INTERNALLY named font families for several fonts (containing nonstandard characters). Maybe that is why the enumeration fails and it never actually gets to Noto in the first place?

Could somebody check if Thorium/Supermium still gets all system fonts if the following fonts are installed in the system?

The "C.A.Gatingas" font was renamed internally by removing the dots, as the font was crashing several kinds of software, but I am going to pack it too (it's the entire reason why I thought of this problem in the first place). "Fanfarron" still has a diacritical symbol internally, while "a-e-i-o-u" has "_". "Metalona" seems to have "*". "hit-me-punk.01" has "," and "!" internally.

[Nonstandardly internally named fonts.zip](https://github.com/Alex313031/thorium-win7/files/14746909/Nonstandardly.internally.named.fonts.zip)

I tried to specify "INTERNALLY" several times, as I am referring to the internal font name, not the filename or anything else.

**Comment by Alex313031** [comment]
@Templayer @JaegerFox This has been fixed in this commit > https://github.com/Alex313031/thorium-legacy/commit/fdeb628070a2481fe5695bcf4069afde64bf406b#diff-02a23746537481b5b5e961197ae121bcdb6227527212aca8cc096f0433aa00f3

Next builds should have it fixed.

**Comment by Templayer** [comment]
So I wasn't going crazy the entire time and it really is/was an issue.

Great! I was worried there for a sec, but the small pink elephant in the corner told me everything was going to be OK. YAY!

**Comment by Alex313031** [comment]
@Templayer Yeah, it was an issue even in M109, which is strange considering this had official Win7 support.

**Comment by Templayer** [comment]
> @Templayer Yeah, it was an issue even in M109, which is strange considering this had official Win7 support.

I'm still in 122 for Win7. When will the Thorium Legacy with this fix arrive so I can test if this was fixed or not?

**Comment by Alex313031** [comment]
@Templayer Building new releases for XP and 7 right now! This release is still based on M122, but has alot of fixes from win32ss, myself, and upstream, as well as backported features from regular M124 Thorium. Stay tuned!
