### ISSUE TITLE
Add Thorium into Scoop repo

### ISSUE THREAD

**Issue by bt4ibwem8** [Alex313031/thorium-legacy#39]
I am using Scoop for installing/uninstalling apps on Windows 7. It is great tool to update apps in Linux-style, all at once instead of update each app separately. I found Thorium build in [unofficial ](https://github.com/anderlli0053/DEV-tools/blob/master/bucket/Thorium-AVX2.json)repo but win7 build is nowhere...
What do you think about the idea to add it into **extras** bucket?

**Comment by Templayer** [comment]
I had the same issue with Chocolatey...
