### ISSUE TITLE
Skewed text positioning when using "Force GDI font rendering" -flag

### ISSUE THREAD

**Issue by ATB57791** [Alex313031/thorium-legacy#69]
**System Details**
 - OS: Windows 7 64 bit
 - Thorium Version: 122.0.6261.158

**Problem**
When using the "Force GDI font rendering" -flag, the text is not aligned to the center. This issue was present in older versions of Supermium, but it was fixed. However, it is not fixed in any of the Thorium builds. More info here:
https://github.com/win32ss/supermium/issues/285

**Comment by Alex313031** [comment]
@ATB57791 I commented there. I can't fix it without him sharing the changes he made to those submodules.

**Comment by Alex313031** [comment]
@ATB57791 Fixed now.
