### ISSUE TITLE
Thorium-XP - Prevent Screensaver When Watching Youtube

### ISSUE THREAD

**Issue by dribgnikcom** [Alex313031/thorium-legacy#70]
The Windows XP screensaver initiates during Youtube playback.  I also had this problem on other modern Chrome-based browsers on XP but not on Firefox-based ones.  Perhaps a fix could be implemented?  Thanks and great job.

It is completely stable for me, unlike Supermium.

**Comment by Alex313031** [comment]
@dribgnikcom That would be something you should hit up win32ss with. I'm not familiar enough with Windows XP development to know how to get it to do this. I could probably find where in the code, but I wouldn't know what to add to make it tell XP to halt the screensaver service when video is playing.

**Comment by dribgnikcom** [comment]
Thanks.  I opened an issue on the Supermium github:

[Windows XP - Prevent Screensaver When Watching Youtube #574](https://github.com/win32ss/supermium/issues/574)

If you could chime in there, I would appreciate it as well.  Thanks!

**Comment by IDA-RE-things** [comment]
Hello, @dribgnikcom 
my alternative DLL for this browsers for XP has this feature added. You can try if it works fine or no.
https://github.com/IDA-RE-things/Chrome-xp-api-adapter/releases

**Comment by IDA-RE-things** [comment]
Hello, @dribgnikcom 
my alternative DLL for this browsers for XP has this feature recently added. You can try if it works fine or no.
https://github.com/IDA-RE-things/Chrome-xp-api-adapter/releases

**Comment by Alex313031** [comment]
@dribgnikcom @IDA-RE-things Fixed in latest release > https://github.com/Alex313031/thorium-legacy/releases/tag/122.0.6261.171
