### ISSUE TITLE
Thorium-XP - SSE4.2 Build

### ISSUE THREAD

**Issue by dribgnikcom** [Alex313031/thorium-legacy#71]
Currently, Thorium-XP is SSE2 only...  Would it be possible to get an SSE4.2 build for better performance?  I believe XP supports up to SSE4.2 natively (and there might be some user mods for AVX, but that's beyond the scope of this request).

It does run pretty good so far on SSE2 though, I should say.  Thanks and great work.

**Comment by Alex313031** [comment]
@dribgnikcom Yes, I will make SSE2, SSE3, and SSE4.1 builds for both 32 bit and 64 bit XP/Vista releases.

See the __UPDATE:__ section at the very bottom of the latest release > https://github.com/Alex313031/thorium-legacy/releases/tag/M122.0.6261.168

**Comment by Alex313031** [comment]
@fenopa You could use the SSE4.1 32 Bit build build I just made for XP/Vista. The only difference to the Win7+ versions is the addition of progwrp.dll

https://github.com/Alex313031/thorium-legacy/releases/tag/M122.0.6261.169
