### ISSUE TITLE
DNS Capability Not Matching Supermium

### ISSUE THREAD

**Issue by narinishi** [Alex313031/thorium-legacy#72]
**System Details**
 - OS: Windows 8.1 64-bit
 - Thorium Version 122.0.6261.168

**Problem**
I am using a local DNS proxy which supports Secure SNI, however Cloudflare's test shows Thorium as not utilizing it.

**Screenshots**
Test result in Thorium
![image](https://github.com/Alex313031/thorium-legacy/assets/118132227/c4458ba1-3d5c-4efd-a2e3-949adb2f6a1f)
Test result in Supermium
![image](https://github.com/Alex313031/thorium-legacy/assets/118132227/9f4ae545-5dce-4be9-866d-76653ec8aa24)

**Additional Notes**
"Encrypt the names of sites that you visit" disabled in both browsers.
URL for Cloudflare SNI test site: https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by gz83** [comment]
reroute to https://github.com/Alex313031/Thorium-Win/issues/199
