### ISSUE TITLE
should remove --disable-encryption from THORIUM.BAT

### ISSUE THREAD

**Issue by xdeadstokex** [Alex313031/thorium-legacy#75]
the flag is rather annoying than it actually is helpful, because when the flag is on, every time you close the browser, every log-in reset, such as yt, github, fb, etc. The flag can be removed mannually by notepad or any editor, but I just want to let you know, because that may affect those who use "portable" mode without knowing how their log-in keep reset.

Note: The thorium version this post mentioned is m122 v3

**Comment by Alex313031** [comment]
@xdeadstokex Done!
