### ISSUE TITLE
thorium policies point to chrome registry keys

### ISSUE THREAD

**Issue by Juesto** [Alex313031/thorium-legacy#78]
wouldnt the policies not apply since its set to policies\google\chrome instead of policies\thorium or similar?
that's what keeping me from using the policies archive

**Comment by nicolaasjan** [comment]
Thorium recognizes policies from:
`HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium`

![screenshot_20240425](https://github.com/Alex313031/thorium-legacy/assets/14093220/1340ee59-4413-439b-b2d1-71f872e58b87)

**Comment by Juesto** [comment]
then the policy files provided are wrong, correct?
wouldn't it be better for thorium policies to be under its own name?

**Comment by nicolaasjan** [comment]
> the policy files provided

Where did you find these files?

**Comment by Juesto** [comment]
> > the policy files provided
> 
> Where did you find these files?

its in the latest release, its just google policy definition files

**Comment by nicolaasjan** [comment]
> its in the latest release, its just google policy definition files

Found them.
They are [under a previous release](https://github.com/Alex313031/thorium-legacy/releases/tag/M122.0.6261.158).

**Comment by Alex313031** [comment]
@Juesto @nicolaasjan The latest policies in the latest release are incorrect. Next release will have this corrected.
