### ISSUE TITLE
Thorium eating up to 100% CPU on their (thorium.rocks) home page. on not so fast computers

### ISSUE THREAD

**Issue by IDA-RE-things** [Alex313031/thorium-legacy#81]
Because you use "Canvas2D Shadow Demo" on it.
Can it be moved to another place, available by the click on it ?
I come there to that page, using Thorium build for XP using "middle notebook" level of computer power. Without script blockers etc.

<hr>

![2](https://github.com/Alex313031/thorium-legacy/assets/9424365/72a5638a-2652-4549-9531-0a0def7e2b58)

<hr>

![1](https://github.com/Alex313031/thorium-legacy/assets/9424365/e472c0b2-a531-423e-8cdc-f3c0dd1e3cc3)

**Comment by IDA-RE-things** [comment]
**_Also here:_**
<hr>

![3](https://github.com/Alex313031/thorium-legacy/assets/9424365/b3820ccf-d270-47c1-af1b-9bb43220cf11)

**Comment by Alex313031** [comment]
@IDA-RE-things Yeah, I need to remove some .js, and compress some images. The site is pretty heavy considering it is simple.
