### ISSUE TITLE
Misinformation in M122.0.6261.169 release notes

### ISSUE THREAD

**Issue by roytam1** [Alex313031/thorium-legacy#82]
> SSE2 builds are not provided for x64, since it doesn't make sense. Every x64 CPU except the very first x64 CPU (The original 1st Gen AMD Opteron from 2003) has SSE3.

Actually many 1st gen of Athlon 64 (FX) processors has no SSE3, namely:
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22ClawHammer%22_(C0_&_CG,_130_nm)
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22Newcastle%22_(CG,_130_nm)
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22Winchester%22_(D0,_90_nm)
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22SledgeHammer%22_(C0_&_CG,_130_nm)
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22ClawHammer%22_(CG,_130_nm)
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22ClawHammer%22_(C0_&_CG,_130_nm)_2
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22Odessa%22_(CG,_130_nm)
https://en.wikipedia.org/wiki/List_of_AMD_Athlon_64_processors#%22Oakville%22_(D0,_90_nm)

i.e. AMD processors released on or before Oct 2004 has no SSE3.

**Comment by K4sum1** [comment]
@Alex313031 I was going to make an issue about this, or more specifically that I can't find a difference between SSE2-AVX2 and that there's no reason that I can find to build anything beyond SSE2.

My data is here, and it's what influenced me to make only SSE2 builds for r3dfox.
https://board.eclipse.cx/viewtopic.php?t=669

**Comment by Alex313031** [comment]
@roytam1 Well, I meant Bulldozer based FX
