### ISSUE TITLE
Errors on Sync in the Windows XP Application Log

### ISSUE THREAD

**Issue by DaveH1** [Alex313031/thorium-legacy#88]
Windows XP SP3 32 bit
Thorium 122.0.6261.171

I've just tried using the Google Sync function for the first time, and it works well, both on Thorium and Supermium (122.0.6261.152).
One issue though is that both browsers now throw an informational error into the Windows Application log when they are launched.
This did not happen before Sync was enabled.

![Clipboard-1](https://github.com/Alex313031/thorium-legacy/assets/6755753/8506ceb1-98e9-4a77-91c7-5500dc109b34)

Running Supermium produces exactly the same error, but obviously saying 'Supermium' where the screen grab says 'Thorium'!
Any idea why this is happening?
Is it because the browsers aren't properly installed into Windows, or is this a message from Google?
Cheers,
Dave.

**Comment by DaveH1** [comment]
Just to update this.
I have now installed the latest 64 bit Google Chrome on the Windows 10 side of my machine, and it's throwing exactly the same error into the Windows Application log every time it's started!
So, I guess this is a general Chrome problem, nothing unique to Thorium (or Supermium).
I've found very little about it on a search, nobody has produced any explanation as to why it's happening or how to fix it!
Sorry for the now apparently irrelevant query.
Cheers, Dave.

**Comment by Alex313031** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:components/policy/core/common/remote_commands/remote_commands_service.cc;l=222?q=remote_commands_service.cc

Seems to be when enterprise policy for remote desktop isn't configured. See that line in the source code. I can make the warning into a commandline warning, rather than spamming the system log.

**Comment by DaveH1** [comment]
Thanks Alex!
It would be good if you could at least suppress the warnings in Thorium.
It's obviously a general Chromium problem, though.
How would you configure 'enterprise policy for remote desktop'?

**Comment by Alex313031** [comment]
@DaveH1 Well, you could look in the policy templates for policies regarding remote desktop. It is unlikely that these would be applicable to or work on XP though.

**Comment by DaveH1** [comment]
Thanks Alex. As I said earlier, these warnings are also happening with the latest Google Chrome on Windows 10, so it's nothing to do with Thorium specifically. Strange that nobody seems to know why it's happening.
Cheers, Dave.
