### ISSUE TITLE
Thorium Win7 - Crashing on Aliexpress

### ISSUE THREAD

**Issue by dribgnikcom** [Alex313031/thorium-legacy#95]
System: Ivy Bridge
OS: Windows 7 latest service pack and updates
Thorium versions 108 and 122 (AVX build)

Aliexpress made some change to their site recently which is causing Thorium to crash for me while browsing it.  This happened on Version 108, so I updated to version 122 but I still got the crash.  Then I created a new profile to rule that out and only installed ublock origin.  So maybe it's a combination of those things.

The symptom is that while browsing Aliexpress for a little bit, the browser becomes unresponsive and has to be forcibly closed...  Then I need to manually kill the thorium process in task manager.

**Comment by Alex313031** [comment]
@dribgnikcom Can you try the latest M109 release from this repo?

Also can you send me an exact URL that this happens on, so I can try to reproduce it on my end?

**Comment by dribgnikcom** [comment]
@Alex313031 - Hi Alex, thanks for the quick response.  It wasn't always this way -- they must have changed something on their page that's causing this behavior.

To replicate the issue - browse the listings, choose an item, scroll down, choose related items, open multiple tabs of related items, etc...

I'm also going to test on my Windows 10 AVX2 Haswell machine to see if it happens there too.

**Comment by crudebuster** [comment]
Strange, I can browse Aliexpress with no problem with my Thorium 109 AVX Win7. Just disabled UO on the page and it loads fine.

**Comment by dribgnikcom** [comment]
> Strange, I can browse Aliexpress with no problem with my Thorium 109 AVX Win7. Just disabled UO on the page and it loads fine.

Yes -- you're right.  The problem is not unique to Thorium.  I download RobRich's AVX build of Chromium (v109.0.5412.0-r1069239-win64-avx) and got the same result...  you say you disabled UO -- hmmm maybe I'll give that a shot.

The way I easily reproduce the browser hanging is to go to an item, then scroll down, open a new tab with a recommended or related item, then open a new tab for a related item from that tab, and on and on until it crashes shortly after...

I still need to test this on other machines to see if it occurs there as well.

**Comment by dribgnikcom** [comment]
Ok, I am almost certain that it was JDownloader that was the cause...  I removed it and everything seems fine now...  and it would explain why the issue was persistent among different versions of Chrome as plugins (read: not extensions) persist between new user profiles.
