### ISSUE TITLE
Which of them should I use MMX, SSE, SSE2, SSE3, SSSE3, EM64T?

### ISSUE THREAD

**Issue by huv9** [Alex313031/thorium-legacy#98]
I don't know what I should use and which is best
windows 7 64
ram 4gb
![1](https://github.com/Alex313031/thorium-legacy/assets/143056014/a7990711-5d64-4ee4-a952-d7509cf4e448)
@Alex313031 Thank you for this beautiful project. I hope you maintain it

**Comment by gz83** [comment]
Please choose SSE3 version

**Comment by huv9** [comment]
> Please choose SSE3 version

Thank you @gz83
